apiVersion: v1
kind: Service
metadata:
  name: {{include "backend-nodejs.name" .}}
  labels: {{- include "backend-nodejs.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "backend-nodejs.selectorLabels" . | nindent 4}}
